name: C/C++ CI
on:
  push:
    branches: [master]
jobs:
  ubuntu:
    name: Ubuntu
    strategy:
      matrix:
        cpp_standard: [20]
        compiler:
          - { cxx: g++-10 }
          - { cxx: clang++-10 }
          - { cxx: clang++-11 }
          - { cxx: clang++-12 }
        os: [ubuntu-20.04]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Install conan
        run: python3 -m pip install conan
      - name: CMake configuration
        run: >
          cmake --preset default
          -DCMAKE_BUILD_TYPE=RELEASE
          -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}}
          -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
      - name: Build tests
        run: cmake --build --preset test -j$(nproc)
      - name: Run tests
        run: ctest --preset ci -j$(nproc)
