name: C/C++ CI
on:
  push:
    branches: [master]
jobs:
  ubuntu:
    name: Ubuntu
    strategy:
      matrix:
        cpp_standard: [20]
        compiler:
          - { cxx: g++-9 }
          - { cxx: g++-10 }
          - { cxx: clang++-10 }
          - { cxx: clang++-11 }
          - { cxx: clang++-12 }
        os: [ubuntu-20.04]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: install poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python
      - name: CMake configuration
        run: >
          cmake -B build -S $GITHUB_WORKSPACE
          -DCMAKE_BUILD_TYPE=RELEASE -DPoetry_DIR=$HOME/.poetry/bin
          -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}}
          -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
      - name: Build
        run: cmake --build build --config release
      - name: Run tests
        run: ctest
        working-directory: build/tests
